# Generated by Django 4.2.10 on 2024-02-26 01:19

from django.db import migrations, models
import enumfields.fields
import tournament.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('state', enumfields.fields.EnumField(default='WAITING', enum=tournament.models.TournamentState, max_length=10)),
            ],
        ),
    ]
