# Generated by Django 4.2.10 on 2024-02-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('is_user1_following_user2', models.BooleanField(default=False)),
                ('is_user2_following_user1', models.BooleanField(default=False)),
                ('user1_followed_user2_at', models.DateTimeField(default=-1)),
                ('user2_followed_user1_at', models.DateTimeField(default=-1)),
            ],
        ),
    ]
